# Generated by Django 3.2.10 on 2023-03-29 18:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Set_Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('last_date', models.DateField()),
                ('questions', models.TextField()),
                ('time_limit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Check_Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=255)),
                ('email_id', models.CharField(max_length=255, validators=[django.core.validators.EmailValidator()])),
                ('profile', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('age', models.PositiveIntegerField()),
                ('status_after_interview', models.CharField(blank=True, max_length=255)),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('interview_details', models.TextField(blank=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.set_interview')),
            ],
        ),
    ]
